using TrevizaniRoleplay.Core.Globalization;
using TrevizaniRoleplay.Domain.Enums;

namespace TrevizaniRoleplay.Core.Extensions;

public static class LogTypeExtensions
{
    public static string GetDescription(this LogType logType)
    {
        return logType switch
        {
            LogType.Staff => Resources.Staff,
            LogType.Faction => Resources.Faction,
            LogType.FactionChat => Resources.FactionChat,
            LogType.Money => Resources.Money,
            LogType.Sell => Resources.Sell,
            LogType.Entrance => Resources.Entrance,
            LogType.Exit => Resources.Exit,
            LogType.Death => Resources.Death,
            LogType.Weapon => Resources.Weapon,
            LogType.NameChange => Resources.NameChange,
            LogType.CharacterDelete => Resources.CharacterDelete,
            LogType.PlateChange => Resources.PlateChange,
            LogType.Advertisement => Resources.Advertisement,
            LogType.GovernmentAdvertisement => Resources.GovernmentAdvertisement,
            LogType.DeliverItem => Resources.DeliverItem,
            LogType.DropItem => Resources.DropItem,
            LogType.GetGroundItem => Resources.GetGroundItem,
            LogType.StealItem => Resources.StealItem,
            LogType.Smuggler => Resources.Smuggler,
            LogType.GiveItem => Resources.GiveItem,
            LogType.PutPropertyItem => Resources.PutPropertyItem,
            LogType.GetPropertyItem => Resources.GetPropertyItem,
            LogType.PutVehicleItem => Resources.PutVehicleItem,
            LogType.GetVehicleItem => Resources.GetVehicleItem,
            LogType.FactionVehicleRepair => Resources.FactionVehicleRepair,
            LogType.PlayerVehicleRepair => Resources.PlayerVehicleRepair,
            LogType.SpawnVehicle => Resources.SpawnVehicle,
            LogType.ParkVehicle => Resources.ParkVehicle,
            LogType.HealMe => Resources.HealMe,
            LogType.PrivateMessages => Resources.PrivateMessages,
            LogType.Mask => Resources.Mask,
            LogType.VehicleDestruction => Resources.VehicleDestruction,
            LogType.Hack => Resources.Hack,
            LogType.Drug => Resources.Drug,
            LogType.LockBreak => Resources.LockBreak,
            LogType.HotWire => Resources.HotWire,
            LogType.Dismantling => Resources.Dismantling,
            LogType.Breakin => Resources.Breakin,
            LogType.StealProperty => Resources.StealProperty,
            LogType.ViewCrackDenSales => Resources.ViewCrackDenSales,
            LogType.EditPropertyFurniture => Resources.EditPropertyFurniture,
            LogType.GlobalOOCChat => Resources.GlobalOOCChat,
            LogType.StaffChat => Resources.StaffChat,
            LogType.PutInVehicle => Resources.PutInVehicle,
            LogType.RemoveFromVehicle => Resources.RemoveFromVehicle,
            LogType.Company => Resources.Company,
            LogType.CompanyAdvertisement => Resources.CompanyAdvertisement,
            LogType.MechanicTunning => Resources.MechanicTunning,
            LogType.Job => Resources.Job,
            LogType.DoubleIdentity => Resources.DoubleIdentity,
            LogType.Info => Resources.Info,
            LogType.UseItem => Resources.UseItem,
            LogType.GetBodyItem => Resources.GetBodyItem,
            LogType.Premium => Resources.Premium,
            LogType.SellPropertyFurniture => Resources.SellPropertyFurniture,
            LogType.Donate => Resources.Donate,
            LogType.Cellphone => Resources.Cellphone,
            LogType.Buy => Resources.Buy,
            LogType.Fix => Resources.Fix,
            LogType.Attributes => Resources.Attributes,
            LogType.General => Resources.General,
            LogType.ICChat => Resources.ICChat,
            LogType.OOCChat => Resources.OOCChat,
            LogType.ViewLogs => Resources.ViewLogs,
            _ => logType.ToString(),
        };
    }
}